# Generated by Django 3.1.2 on 2022-02-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxndatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='reactant_smarts2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='reactant_smarts3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='reactant_smarts4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='reactant_smarts5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='suggested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='cat1_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='cat2_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='cat3_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='reactant_smiles2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='reactant_smiles3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='reactant_smiles4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='reactant_smiles5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='rgt1_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='rgt2_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='rgt3_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='rgt4_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='rgt5_eq',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='suggested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='svt1_vol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='svt2_vol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='svt3_vol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='reactant_smarts2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='reactant_smarts3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='reactant_smarts4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='reactant_smarts5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='suggested',
            field=models.BooleanField(default=True),
        ),
    ]
