# Generated by Django 3.1.2 on 2022-02-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxndatapp', '0003_auto_20220227_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='common_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
