# Generated by Django 3.1.2 on 2022-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxndatapp', '0006_auto_20220228_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='alias',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='transformation',
            name='product_smiles',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='transformation',
            name='reactant_smiles',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
