# Generated by Django 3.1.2 on 2022-03-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxndatapp', '0007_auto_20220301_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='product_smiles',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='condition',
            name='reactant_smiles',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
