# Generated by Django 3.1.2 on 2022-03-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxndatapp', '0008_auto_20220304_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='product_smiles',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
