# Generated by Django 3.1.2 on 2022-02-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxndatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='name',
            field=models.CharField(default='rxn', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transformation',
            name='product_smarts',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='reactant_smarts',
            field=models.CharField(max_length=50),
        ),
    ]
